In [1]:
import torch
import numpy as np

In [5]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [8]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor \n{x_ones} \n")

x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f"Random Tensor \n{x_rand}\n")

Ones Tensor 
tensor([[1, 1],
        [1, 1]]) 

Random Tensor 
tensor([[0.1466, 0.5627],
        [0.9812, 0.6411]])



In [10]:
shape = (2, 3)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor:\n{rand_tensor}\n")
print(f"Ones Tensor:\n{ones_tensor}\n")
print(f"Zeros Tensor:\n{zeros_tensor}\n")

Random Tensor:
tensor([[0.1654, 0.1681, 0.3021],
        [0.8127, 0.8080, 0.8904]])

Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])



In [11]:
tensor = torch.rand(3, 4)

print(f"Shape of Tensor : {tensor.shape}")
print(f"Datatype of Tensor : {tensor.dtype}")
print(f"Device Tensor is stored on : {tensor.device}")

Shape of Tensor : torch.Size([3, 4])
Datatype of Tensor : torch.float32
Device Tensor is stored on : cpu


In [17]:
is_available = torch.cuda.is_available()
print(f"Is GPU available {is_available}")

if is_available:
    tensor = tensor.to('cuda')

Is GPU available True
